import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import MoFooter from "../servercomp/moFooter"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode,
  title: string;
}>) {

  const regiao:string = "pt"
  const url:string = "/" 

  return (
    <html lang="pt-br">
      <body className={inter.className}>     
        {children}
      </body>
    </html>
  );
}
